// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WiSave.Incomes.Projections.Postgres;

#nullable disable

namespace WiSave.Incomes.Projections.Postgres.Migrations
{
    [DbContext(typeof(ProjectionsDbContext))]
    [Migration("20260622220808_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projections")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WiSave.Incomes.Projections.Postgres.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Subcategories", "WiSave.Incomes.Projections.Postgres.Entities.CategoryEntity.Subcategories#SubcategoryEntity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("SortOrder");

                            b1.ToJson("subcategories");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("categories", "projections");
                });
#pragma warning restore 612, 618
        }
    }
}
